version: '3.6'
services:
  mongo:
    image: 'mongo:4.4'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwer1234

  server:
    image: 'node:14'
    ports:
      - 9090:9090
    environment:
#      - NODE_ENV=production
      - NODEJS_MONGO_DB_URI=mongodb://admin:qwer1234@mongo:27017
#    user: "node"
    working_dir: /home/node/app/service
    volumes:
      - ./:/home/node/app
    command: "node main.js"


#  client:
#    image: 'node:14'
#    ports:
#      - 3000:80
##    environment:
#    #      - NODE_ENV=production
##    user: "node"
#    working_dir: /home/node/app
#    volumes:
#      - ./:/home/node/app
#    command: "npm start"

  client:
    image: nginx:1.19.2
    ports:
      - 3000:80
    volumes:
      - ./build:/usr/share/nginx/html

  envoy:
    build:
      context: service
      dockerfile: service/docker/envoy/Dockerfile
    image: fiblab/envoy
    ports:
      - "8080:8080"
#    links:
#      - node-server

#  nginx:
#    image: nginx:1.19.2
#    ports:
#      - 127.0.0.1:1443:1443
#    volumes:
#      - ./config/nginx.conf:/etc/nginx/nginx.conf
#    secrets:
#      - nginx.cert
#      - nginx.key

secrets:
  nginx.cert:
    file: ./service/cert/nginx.cert
  nginx.key:
    file: ./service/cert/nginx.key
