
# ENV
alpha: 0.53

track_path: './raw_data/geolife/real.npy'

traj_length: 100

# PPO
episode: 20000
capacity: 1000
gamma: 0.99
lam: 0.95
value_learning_rate: 0.001
policy_learning_rate: 0.001
discriminator_learning_rate: 0.001
batch_size: 30
policy_iter: 10
disc_iter: 10
value_iter: 10
epsilon: 0.2
entropy_weight: 0.0001
train_iter: 10
clip_grad: 10

# ATNetwork
total_locations: 9100
time_scale: 100
loc_embedding_dim: 32
tim_embedding_dim: 10
hidden_dim: 64
bidirectional: False
device: 'cuda'
data: 'geolife'
starting_sample: 'zero'
starting_dist: null
embedding_net: null

# Recover_CNN
act_embedding_dim: 9
recover_cnn_reward_ratio: 0.5
recover_cnn_learning_rate: 0.0003

model_save_interval: 1000
test_data_path: './raw_data/geolife/real.npy'
